<?php
/**
 * MythTV in detail...
 *
 * @url         $URL: svn+ssh://svn.mythtv.org/var/lib/svn-www/www.mythtv.org/htdocs/pages/detail.php $
 * @date        $Date: 2008-11-15 21:02:20 -0800 (Sat, 15 Nov 2008) $
 * @version     $Revision: 125 $
 * @author      $Author: xris $
 * @copyright   MythTV
 *
 * @package     mythtv.org
 *
/**/
?>
<div id="detail-mythweb" class="detail">
    <a name="mythweb"></a>
    <h1>MythWeb</h1>

    <p>
    <div style="float: right; margin-left: 2em">
    <?php tv_thumb('mythweb_listing.png', 'tv_black', 'l', 'a', '#e6e6f0')  ?>
    <?php tv_thumb('mythweb_details.png', 'tv_black', 'r', 'a', '#e6e6f0')  ?>
    </div>
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    </p>

    <p style="clear: right">
    <div style="float: left; margin-right: 2em">
    <?php tv_thumb('mythweb_upcoming.png', 'tv_black', 'l', 'a', '#e6e6f0')  ?>
    <?php tv_thumb('mythweb_recorded.png', 'tv_black', 'r', 'a', '#e6e6f0')  ?>
    </div>
    Maybe talk some more, and show some more screenshots...
    Maybe talk some more, and show some more screenshots...
    Maybe talk some more, and show some more screenshots...
    Maybe talk some more, and show some more screenshots...
    Maybe talk some more, and show some more screenshots...
    Maybe talk some more, and show some more screenshots...
    Maybe talk some more, and show some more screenshots...
    </p>

    <p>
    <div style="float: right; margin-left: 2em">
    <?php tv_thumb('mythweb_video.png',      'tv_black', 'l', 'a', '#e6e6f0')  ?>
    <?php tv_thumb('mythweb_recdetails.png', 'tv_black', 'r', 'a', '#e6e6f0')  ?>
    </div>
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    So this is the place where I would talk about MythWeb...
    Show a few screenshots...
    </p>
</div>