<?php
/**
 * Screenshots of all of the coolness...
 *
 * @url         $URL$
 * @date        $Date$
 * @version     $Revision$
 * @author      $Author$
 * @copyright   MythTV
 *
 * @package     mythtv.org
 *
/**/

// Which section are we in?
    $Nav = 'about';

// Load the global page header
    require_once 'pages/header.php';
?>


Detail article (containing screenshots) coming soon.

<h3>MythWeb</h3>

<p>
<div style="float: right; margin-left: 2em">
<?php tv_thumb('mythweb_listing.png', 'tv_black', 'r', 'a')  ?>
<?php tv_thumb('mythweb_details.png', 'tv_black', 'l', 'a')  ?>
</div>
So this is the place where I would talk about MythWeb...
Show a few screenshots...
So this is the place where I would talk about MythWeb...
Show a few screenshots...
So this is the place where I would talk about MythWeb...
Show a few screenshots...
So this is the place where I would talk about MythWeb...
Show a few screenshots...
So this is the place where I would talk about MythWeb...
Show a few screenshots...
So this is the place where I would talk about MythWeb...
Show a few screenshots...
</p>

<p style="clear: right">
<div style="float: left; margin-right: 2em">
<?php tv_thumb('mythweb_upcoming.png', 'tv_white', 'r', 'a')  ?>
<?php tv_thumb('mythweb_recorded.png', 'tv_white', 'l', 'a')  ?>
</div>
Maybe talk some more, and show some more screenshots...
Maybe talk some more, and show some more screenshots...
Maybe talk some more, and show some more screenshots...
Maybe talk some more, and show some more screenshots...
Maybe talk some more, and show some more screenshots...
Maybe talk some more, and show some more screenshots...
Maybe talk some more, and show some more screenshots...
</p>

<?php
// Load the global page footer
    require_once 'pages/footer.php';

